apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://github.com/cert-manager/cert-manager/issues/2482#issuecomment-753364467
resources:
  # - 'https://github.com/cert-manager/cert-manager/releases/download/v1.12.2/cert-manager.crds.yaml'
  - 'https://github.com/cert-manager/cert-manager/releases/download/v1.16.1/cert-manager.yaml'
  - cluster-issuer.yaml
